@baseUrl = http://localhost:3000

### /
GET {{baseUrl}}/

### /api/posts
GET {{baseUrl}}/api/posts

### /api/posts/:id
GET {{baseUrl}}/api/posts/1

### /api/nonexistent
GET {{baseUrl}}/api/nonexistent

### static files
GET {{baseUrl}}/images/ciambellone.jpeg
