@baseUrl = http://localhost:3000

### React frontend
GET {{baseUrl}}/

### /bacheca
GET {{baseUrl}}/bacheca

### /bacheca/:id
GET {{baseUrl}}/bacheca/1

### Filter posts by tag
GET {{baseUrl}}/bacheca?tag=dolci

### Search posts
GET {{baseUrl}}/bacheca?search=barbabietola

### Sort posts
GET {{baseUrl}}/bacheca?sortBy=title&order=desc

### Post not found
GET {{baseUrl}}/bacheca/999

### API resource not found
GET {{baseUrl}}/bacheca/1/nonexistent

### static files
GET {{baseUrl}}/images/ciambellone.jpeg
